import { useEffect, useState } from 'react'
import { computeEstimate, fmt } from '../lib/estimate.js'
import { buildStructuredInputs, fetchExplanation } from '../lib/explain.js'

export default function CostChecker({ provider, persona, visitReason, compact = false }) {
  const est = computeEstimate(provider, persona, visitReason)
  const [explanation, setExplanation] = useState(null)

  useEffect(() => {
    let live = true
    setExplanation(null)
    if (!est.available) return
    const inputs = buildStructuredInputs(est, persona, provider, visitReason)
    fetchExplanation(inputs).then((r) => live && setExplanation(r))
    return () => { live = false }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [provider.id, persona.id])

  if (!est.available) {
    return (
      <div className="cc-module">
        <div className="cc-head">
          <span className="label">COST CHECKER</span>
        </div>
        <div className="unavailable">
          We can't estimate your cost for this provider yet: their negotiated rate data
          isn't available for your plan. You're still confirmed in network. We'd rather
          show you nothing than a number we can't stand behind.
        </div>
      </div>
    )
  }

  const elig = persona.eligibility
  const remainingDed =
    elig.deductibleMet != null
      ? Math.max(0, elig.deductibleTotal - elig.deductibleMet)
      : null

  return (
    <div className="cc-module">
      <div className="cc-head">
        <div>
          <div className="label">COST CHECKER · Estimated cost for you</div>
          <div className="cc-range money">
            {est.low === est.high ? fmt(est.low) : `${fmt(est.low)}–${fmt(est.high)}`}
          </div>
        </div>
        <span className={`conf ${est.confidence}`}>{est.confidence} confidence</span>
      </div>

      {!compact && (
        <>
          <div className="ledger">
            <div className="ledger-title">How this is calculated</div>
            {est.lines.map((l) => (
              <div className="ledger-line" key={l.code}>
                <span className="k">
                  {l.description} ({l.code}) · negotiated rate {fmt(l.rate)}
                </span>
                <span className="v money">{fmt(l.patientCost)}</span>
              </div>
            ))}
            {remainingDed != null && (
              <div className="ledger-line">
                <span className="k">Deductible remaining</span>
                <span className="v money">{fmt(remainingDed)} of {fmt(elig.deductibleTotal)}</span>
              </div>
            )}
            {elig.specialistCopay != null && (
              <div className="ledger-line">
                <span className="k">Specialist office visit copay</span>
                <span className="v money">{fmt(elig.specialistCopay)}</span>
              </div>
            )}
            {elig.coinsurance != null && remainingDed === 0 && (
              <div className="ledger-line">
                <span className="k">Your coinsurance after deductible</span>
                <span className="v">{elig.coinsurance * 100}%</span>
              </div>
            )}
            <div className="ledger-line total">
              <span className="k">You'd likely pay</span>
              <span className="v money">
                {est.low === est.high ? fmt(est.low) : `${fmt(est.low)}–${fmt(est.high)}`}
              </span>
            </div>
          </div>

          <div className="ai-panel">
            <span className="ai-tag">✦ In plain language</span>
            {explanation ? (
              <p>{explanation.text}</p>
            ) : (
              <p style={{ opacity: 0.55 }}>Writing your explanation…</p>
            )}
            {explanation && (
              <span className="src">
                {explanation.source === 'llm'
                  ? 'Generated by AI from the calculation above. The AI explains the math; it never changes it.'
                  : 'Template explanation (demo mode, no API key configured). In production this text is AI-generated from the calculation above.'}
              </span>
            )}
          </div>

          <div className="flags">
            <div className="flag">
              ⚑ Skin biopsies, if performed, are billed separately and may involve an
              outside lab. Ask your provider before any add-on procedure.
            </div>
            {est.confidence !== 'High' && (
              <div className="flag">⚑ {est.confidenceReasons[0]}</div>
            )}
          </div>

          <div className="disclaimer">
            This is an estimate based on your plan details and publicly reported rate
            data, not a guaranteed price. Sources: your insurer's real-time benefits
            response · federally required price transparency files (updated{' '}
            {provider.rateDataFreshDays} days ago).
          </div>
        </>
      )}
    </div>
  )
}
